---
services:
  web:
    image: "$IMAGE_URI:$IMAGE_TAG"
    ports:
      - "3000:3000"
    environment:
      - BACKGROUND_COLOR=#b6f5b6
      - APP_NAME=My Dockerized App
      - CUSTOM_TEXT=This was deployed via docker compose!
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
