---
name: CICD Docker Build and Push
on:
  push: 
  workflow_dispatch:

env:
  TEST_TAG: local/app:test
  TEST_CONTAINER_NAME: test_container

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # SOURCE
      - name: Checkout
        uses: actions/checkout@v4

      # SETUP AGENT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # BUILD
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      # TEST
      - name: Test
        run: |
          docker run -d --name ${{ env.TEST_CONTAINER_NAME }} --rm ${{ env.TEST_TAG }}
          sleep 10
          docker ps -a
          docker exec ${{ env.TEST_CONTAINER_NAME }} curl http://127.0.0.1:3000
          docker stop ${{ env.TEST_CONTAINER_NAME }} && docker rm ${{ env.TEST_CONTAINER_NAME }}

      # RELEASE
      - name: Set outputs
        id: myoutputs
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        # https://github.com/docker/build-push-action
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/test:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/test:production
            ${{ secrets.DOCKERHUB_USERNAME }}/test:${{ steps.myoutputs.outputs.sha_short }}