---
name: Super-Linter
on: []
jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          LINTER_RULES_PATH: /
          YAML_CONFIG_FILE: .yaml-lint.yml
          VALIDATE_PYTHON_BLACK: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}